server:
  port: 8100
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/pdfboxapi.logs
spring:
  application:
    pdf:
      create_read:
        path: ./pdfContainer
    security:
      jwt:
        secretKey: uyer6734knig3487204nft3245i9786340o23k4gyt7230.
        expiration: 86400000
  datasource:
    url: jdbc:postgresql://localhost:5432/pdfBox
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


